#PLEASE NOTE: THIS IS A SAMPLE SECRET AND YOU NEED TO REPLACE THE FIELDS WITH YOUR OWN VALUES
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
  namespace: ingress-basic
type: Opaque
stringData :
  eventbus: "<YOUR_VALUE>"
  mongo: "<YOUR_VALUE>"
  neo4jconnection: "<YOUR_VALUE>"
  neo4jpassword: "<YOUR_VALUE>" 