kind: Service
apiVersion: v1
metadata:
  name: social-service
  namespace: ingress-basic
spec:
  ports:
    - name: port80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: port443
      protocol: TCP
      port: 443
      targetPort: 443  
  selector:
    app: social-service
  type: ClusterIP